### ISSUE TITLE
anything here? 

### ISSUE THREAD

**Issue by brlinf-06398** [PLsubfarm61/Project_B#1]
this mod is smaller than betamindy and ca-mod. even ca-mod is made by a single person. you can get some ideas from those mods. you didn't even collaborate with other modders like Project Unity. add some sandbox stuff please. (how does betamindy has a lot more creators than ca-mod while being just a little bit larger)

**Comment by PLsubfarm61** [comment]
There is little content because I haven't finished the mod yet, even in the name it says "[Alpha]"
